module.exports = Object.freeze({
  title: 'Pohjola',
  author: 'Janne Jaanila',
  authorUrl: 'https://github.com/jjaanila',
  publishDate: '2022-02-01',
  monsters: [
    {
      name: 'Thug',
      size: 'medium',
      type: 'humanoid',
      alignment: 'any alignment',
      armorClass: 11,
      armor: 'Leather Armor',
      hitPoints: { throws: 2, sides: 8, constant: 10 },
      speedFt: 30,
      strength: 15,
      dexterity: 11,
      constitution: 14,
      intelligence: 10,
      wisdom: 10,
      charisma: 11,
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 0.5,
      passives: [
        {
          name: 'Pack Tactics',
          description:
            'The thug has advantage on an attack roll against a creature if at least one of the thug’s allies is within 5 ft. of the creature and the ally isn’t incapacitated.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'The thug makes two melee attacks.',
        },
        {
          name: 'Mace',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 1, sides: 6, constant: 2 },
        },
      ],
    },
    {
      name: 'Saltwater Scrag',
      size: 'large',
      type: 'giant',
      alignment: 'chaotic evil',
      armorClass: 14,
      armor: '',
      hitPoints: { throws: 8, sides: 10, constant: 40 },
      speedFt: 30,
      strength: 18,
      dexterity: 13,
      constitution: 20,
      intelligence: 7,
      wisdom: 9,
      charisma: 7,
      skills: [{ name: 'perception', modifier: 2 }],
      senses: ['darkvision 60ft.', 'passive Perception 12'],
      languages: ['aquan', 'giant'],
      challengeRating: 5,
      passives: [
        {
          name: 'Keen Smell',
          description: 'The Saltwater Scrag has advantage on Wisdom (Perception) checks that rely on smell.',
        },
        {
          name: 'Amphibious',
          description: 'The Saltwater Scrag can breath air and water.',
        },
        {
          name: 'Underwater Regeneration',
          description:
            'While at least partially submerged in salt water, regains 10 hit points at the start of its turn. If takes fire or acid damage, this trait does not function at the start of its next turn. Dies only if starts its turn with 0 hit points and does not regenerate.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'The Saltwater Scrag makes two melee attacks: one with is claws and one with its bite.',
        },
        {
          name: 'Bite',
          type: 'melee',
          toHit: 8,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 10, constant: 5 },
          extra:
            'The target is grappled (escape DC 16). Until this grapple ends, the target is restrained, and The Saltwater Scrag cannot bite another target.',
        },
      ],
    },
    {
      name: 'Northern Giant',
      size: 'large',
      type: 'giant',
      alignment: 'neutral evil',
      armorClass: 13,
      armor: '',
      hitPoints: { throws: 10, sides: 12, constant: 40 },
      speedFt: 35,
      strength: 21,
      dexterity: 8,
      constitution: 19,
      intelligence: 5,
      wisdom: 9,
      charisma: 6,
      skills: [{ name: 'perception', modifier: 2 }],
      senses: ['passive Perception 12'],
      damageResistances: ['cold'],
      languages: ['giant'],
      challengeRating: 5,
      passives: [],
      actions: [
        {
          name: 'Multiattack',
          description: 'The giant makes two greatclub attacks.',
        },
        {
          name: 'Greatclub',
          type: 'melee',
          toHit: 8,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 3, sides: 10, constant: 5 },
        },
        {
          name: 'Rock',
          type: 'ranged',
          toHit: 8,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'bludgeoning',
          damage: { throws: 3, sides: 6, constant: 5 },
        },
      ],
    },
    {
      name: 'Swarm of Rats',
      size: 'medium',
      type: 'swarm of tiny beasts',
      alignment: 'unaligned',
      armorClass: 10,
      armor: '',
      hitPoints: { throws: 7, sides: 8, constant: 7 },
      speedFt: 30,
      strength: 9,
      dexterity: 11,
      constitution: 9,
      intelligence: 2,
      wisdom: 10,
      charisma: 3,
      senses: ['darkvision 30ft.', 'passive Perception 10'],
      damageResistances: ['bludgeoning', 'piercing', 'slashing'],
      conditionImmunities: [
        'charmed',
        'frightened',
        'grappled',
        'paralyzed',
        'petrified',
        'prone',
        'restrained',
        'stunned',
      ],
      languages: [],
      challengeRating: 0.25,
      passives: [
        {
          name: 'Keen Smell',
          description: 'The swarm has advantage on Wisdom (Perception) checks that rely on smell.',
        },
        {
          name: 'Swarm',
          description:
            "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny rat. The swarm cannot regain hit points or gain temporary hit points.",
        },
      ],
      actions: [
        {
          name: 'Bite',
          type: 'melee',
          toHit: 2,
          reachFt: 0,
          damageType: 'piercing',
          damage: { throws: 2, sides: 6, constant: 0 },
          extra: '3 (1d6) piercing damage if the swarm has half of its hit points or fewer.',
        },
      ],
    },
    {
      name: 'Körri',
      size: 'tiny',
      type: 'beast',
      alignment: 'neutral evil',
      armorClass: 14,
      armor: '',
      hitPoints: { throws: 2, sides: 4, constant: 0 },
      speedFt: 40,
      strength: 3,
      dexterity: 15,
      constitution: 12,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
      senses: ['darkvision 30ft.', 'passive Perception 13'],
      damageResistances: ['poison'],
      languages: [],
      challengeRating: 0.125,
      passives: [
        {
          name: 'Keen Smell',
          description: 'Körri has advantage on Wisdom (Perception) checks that rely on smell.',
        },
      ],
      actions: [
        {
          name: 'Claws',
          type: 'melee',
          toHit: 2,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 6, constant: 0 },
        },
      ],
    },
    {
      name: 'Bandit Captain',
      size: 'medium',
      type: 'humanoid',
      alignment: 'neutral evil',
      armorClass: 15,
      armor: 'Studded leather',
      hitPoints: { throws: 10, sides: 8, constant: 20 },
      speedFt: 30,
      strength: 15,
      dexterity: 16,
      constitution: 14,
      intelligence: 14,
      wisdom: 11,
      charisma: 14,
      senses: ['passive Perception 10'],
      languages: ['common', 'elvish'],
      challengeRating: 2,
      passives: [],
      actions: [
        {
          name: 'Multiattack',
          description:
            'The captain makes three melee attacks: two with its scimitar and one with its dagger. Or the captain makes two ranged attacks with its daggers.',
        },
        {
          name: 'Scimitar',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 6, constant: 3 },
        },
        {
          name: 'Dagger',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 4, constant: 3 },
        },
        {
          name: 'Throwing Dagger',
          type: 'ranged',
          toHit: 5,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 4, constant: 3 },
        },
      ],
      reactions: [
        {
          name: 'Parry',
          description:
            'The captain adds 2 to its AC against one melee attack that would hit it. To do so, the captain must see the attacker and be wielding a melee weapon.',
        },
      ],
    },
    {
      name: 'Bandit',
      size: 'medium',
      type: 'humanoid (any race)',
      alignment: 'neutral evil',
      armorClass: 12,
      armor: 'leather armor',
      hitPoints: { throws: 2, sides: 8, constant: 2 },
      speedFt: 30,
      strength: 11,
      dexterity: 12,
      constitution: 12,
      intelligence: 10,
      wisdom: 10,
      charisma: 10,
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 0.125,
      passives: [],
      actions: [
        {
          name: 'Scimitar',
          type: 'melee',
          toHit: 3,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 6, constant: 1 },
        },
        {
          name: 'Light Crossbow',
          type: 'ranged',
          toHit: 3,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 8, constant: 1 },
        },
      ],
    },
    {
      name: 'Kobold',
      size: 'small',
      type: 'humanoid (kobold)',
      alignment: 'lawful evil',
      armorClass: 12,
      armor: 'leather armor',
      hitPoints: { throws: 2, sides: 6, constant: -2 },
      speedFt: 30,
      strength: 7,
      dexterity: 15,
      constitution: 9,
      intelligence: 8,
      wisdom: 7,
      charisma: 8,
      senses: ['passive Perception 18'],
      languages: ['common', 'draconic'],
      challengeRating: 0.125,
      passives: [
        {
          name: 'Sunlight Sensitivity',
          description:
            'While in sunlight, the kobold has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.',
        },
        {
          name: 'Pack Tactics',
          description:
            'The kobold has advantage on an attack roll against a creature if at least one of the kobold’s allies is within 5 ft. of the creature and the ally isn’t incapacitated.',
        },
      ],
      actions: [
        {
          name: 'Dagger',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 4, constant: 2 },
        },
        {
          name: 'Sling',
          type: 'ranged',
          toHit: 4,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'bludgeoning',
          damage: { throws: 1, sides: 4, constant: 2 },
        },
      ],
    },
    {
      name: 'Golem Guardian',
      size: 'large',
      type: 'construct',
      alignment: 'unaligned',
      armorClass: 17,
      armor: '',
      hitPoints: { throws: 17, sides: 10, constant: 85 },
      speedFt: 25,
      strength: 22,
      dexterity: 9,
      constitution: 20,
      intelligence: 3,
      wisdom: 11,
      charisma: 1,
      senses: ['passive Perception 10'],
      languages: ['understands the languages of its creator but can’t speak'],
      challengeRating: 10,
      passives: [
        {
          name: 'Immutable Form',
          description: 'The golem is immune to any spell or effect that would alter its form.',
        },
        {
          name: 'Magic Resistance',
          description: 'The golem has advantage on saving throws against spells and other magical effects.',
        },
        {
          name: 'Magic Weapons',
          description: 'The golem’s weapon attacks are magical.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'The golem makes two slam attacks.',
        },
        {
          name: 'Slam',
          type: 'melee',
          toHit: 10,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 3, sides: 8, constant: 6 },
        },
      ],
    },
    {
      name: 'Deep Gnome',
      size: 'small',
      type: 'humanoid (gnome)',
      alignment: 'neutral good',
      armorClass: 15,
      armor: '(Chain shirt)',
      hitPoints: { throws: 3, sides: 6, constant: 6 },
      speedFt: 20,
      strength: 15,
      dexterity: 14,
      constitution: 14,
      intelligence: 12,
      wisdom: 10,
      charisma: 9,
      senses: ['darkvision 120ft.', 'passive Perception 10'],
      languages: ['gnomish', 'terran', 'undercommon'],
      challengeRating: 0.5,
      passives: [
        {
          name: 'Stone Camouflage',
          description: 'The gnome has advantage on Dexterity (Stealth) checks made to hide in rocky terrain.',
        },
        {
          name: 'Gnome Cunning',
          description: 'The gnome has advantage on Intelligence, Wisdom, and Charisma saving throws against magic.',
        },
        {
          name: 'Innate Spellcasting',
          description:
            'The gnome’s innate spellcasting ability is Intelligence (spell save DC 11). It can innately cast the following spells, requiring no material components:\
          \nCantrips (at will): nondetection (self only) \
          1/day each: blindness, deafness, blur, disguise self',
        },
      ],
      actions: [
        {
          name: 'War Pick',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 8, constant: 2 },
        },
        {
          name: 'Poisoned Dart',
          type: 'ranged',
          toHit: 4,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 8, constant: 2 },
          extra:
            'The target must succeed on a dc 12 constitution saving throw or be poisoned for 1 minute The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.',
        },
      ],
    },
    {
      name: 'Rust Monster',
      size: 'medium',
      type: 'monstrosity',
      alignment: 'unaligned',
      armorClass: 14,
      armor: '(Natural armor)',
      hitPoints: { throws: 22, sides: 8, constant: 22 },
      speedFt: 40,
      strength: 13,
      dexterity: 12,
      constitution: 13,
      intelligence: 2,
      wisdom: 13,
      charisma: 6,
      senses: ['darkvision 60ft.', 'passive Perception 11'],
      languages: [],
      challengeRating: 0.5,
      passives: [
        {
          name: 'Iron Scent',
          description: 'The rust monster can pinpoint, by scent, the location of ferrous metal within 30 feet of it.',
        },
        {
          name: 'Rust Metal',
          description:
            'Any nonmagical weapon made of metal that hits the rust monster corrodes. After dealing damage, the weapon takes a permanent and cumulative -1 penalty to damage rolls. If its penalty drops to -5, the weapon is destroyed. Non magical ammunition made of metal that hits the rust monster is destroyed after dealing damage.',
        },
      ],
      actions: [
        {
          name: 'Bite',
          type: 'melee',
          toHit: 3,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 8, constant: 4 },
        },
        {
          name: 'Antennae',
          description:
            'The rust monster corrodes a nonmagical ferrous metal object it can see within 5 feet of it. If the object isn’t being worn or carried, the touch destroys a 1-foot cube of it. If the object is being worn or carried by a creature, the creature can make a DC 11 Dexterity saving throw to avoid the rust monster’s touch. If the object touched is either metal armor or a metal shield being worn or carried, its takes a permanent and cumulative -1 penalty to the AC it offers. Armor reduced to an AC of 10 or a shield that drops to a +0 bonus is destroyed. If the object touched is a held metal weapon, it rusts as described in the Rust Metal trait.',
        },
      ],
    },
    {
      name: 'Young Gold Dragon',
      size: 'large',
      type: 'dragon',
      alignment: 'lawful good',
      armorClass: 18,
      armor: '(Natural armor)',
      hitPoints: { throws: 17, sides: 10, constant: 85 },
      speedFt: 40,
      strength: 23,
      dexterity: 14,
      constitution: 21,
      intelligence: 16,
      wisdom: 13,
      charisma: 20,
      savingThrows: ['Dex +6', 'Con +9', 'Wis +5', 'Cha +9'],
      skills: [
        { name: 'insight', modifier: 5 },
        { name: 'perception', modifier: 9 },
        { name: 'persuasion', modifier: 9 },
        { name: 'stealth', modifier: 6 },
      ],
      senses: ['blindsight 30ft.', 'darkvision 120ft.', 'passive Perception 19'],
      damageImmunities: ['fire'],
      languages: ['common', 'draconic'],
      challengeRating: 10,
      passives: [
        {
          name: 'Amphibious',
          description: 'The dragon can breathe air and water.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'The dragon makes three attacks: one with its bite and two with its claws.',
        },
        {
          name: 'Bite',
          type: 'melee',
          toHit: 10,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 2, sides: 10, constant: 6 },
        },
        {
          name: 'Claw',
          type: 'melee',
          toHit: 10,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 2, sides: 6, constant: 6 },
        },
        {
          name: 'Breathe Weapons (Recharge 5-6)',
          description:
            'The dragon uses one of the following breath weapons. Fire Breath. The dragon exhales fire in a 30-foot cone. Each creature in that area must make a DC 17 Dexterity saving throw, taking 55 (10d10) fire damage on a failed save, or half as much damage on a successful one. Weakening Breath. The dragon exhales gas in a 30-foot cone. Each creature in that area must succeed on a DC 17 Strength saving throw or have disadvantage on Strength-based attack rolls, Strength checks, and Strength saving throws for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.',
        },
      ],
    },
    {
      name: 'Barbarian',
      size: 'medium',
      type: 'humanoid (any race)',
      alignment: 'lawful neutral',
      armorClass: 13,
      armor: '(Hide armor)',
      hitPoints: { throws: 9, sides: 8, constant: 0 },
      speedFt: 30,
      strength: 13,
      dexterity: 11,
      constitution: 10,
      intelligence: 8,
      wisdom: 11,
      charisma: 8,
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 0.25,
      passives: [
        {
          name: 'Pack Tactics',
          description:
            "The barbarian has advantage on an attack roll against a creature if at least one of the barbarian's allies is within 5 ft. of the creature and the ally isn’t incapacitated.",
        },
      ],
      actions: [
        {
          name: 'Two-handed Spear',
          type: 'melee',
          toHit: 3,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 8, constant: 1 },
        },
        {
          name: 'Spear',
          type: 'melee',
          toHit: 3,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 6, constant: 1 },
        },
        {
          name: 'Throw Spear',
          type: 'ranged',
          toHit: 3,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 6, constant: 1 },
        },
      ],
    },
    {
      name: 'Northern Druid',
      size: 'medium',
      type: 'humanoid (any race)',
      alignment: 'neutral evil',
      armorClass: 11,
      armor: '(16 with Bark Skin)',
      hitPoints: { throws: 5, sides: 18, constant: 5 },
      speedFt: 30,
      strength: 10,
      dexterity: 12,
      constitution: 13,
      intelligence: 12,
      wisdom: 16,
      charisma: 11,
      senses: ['passive Perception 14'],
      languages: ['common', 'druidic', 'giant'],
      challengeRating: 2,
      passives: [
        {
          name: 'Spellcasting',
          description:
            'Spellcasting. The druid is a 4th-level spellcaster. Its spellcasting ability is Wisdom (spell save DC 12, +4 to hit with spell attacks). It has the following druid spells prepared: \nCantrips (at will): druidcraft, produce flame, shillelagh 1st level (4 slots): entangle, longstrider, speak with animals, thunderwave 2nd level (3 slots): animal messenger, barkskin',
        },
      ],
      actions: [
        {
          name: 'Quarterstaff',
          type: 'melee',
          toHit: 2,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 1, sides: 6, constant: 0 },
          extra: '(1d8 + 2) bludgeoning damage with shillelagh or if wielded with two hands.',
        },
      ],
    },
    {
      name: 'Death Dog',
      size: 'medium',
      type: 'monstrosity',
      alignment: 'neutral evil',
      armorClass: 12,
      armor: '',
      hitPoints: { throws: 6, sides: 8, constant: 12 },
      speedFt: 40,
      strength: 15,
      dexterity: 14,
      constitution: 14,
      intelligence: 3,
      wisdom: 13,
      charisma: 6,
      skills: [
        { name: 'Perception', modifier: 5 },
        { name: 'stealth', modifier: 4 },
      ],
      senses: ['darkvision 120ft.', 'passive Perception 15'],
      languages: [],
      challengeRating: 1,
      passives: [
        {
          name: 'Two-Headed',
          description:
            'The dog has advantage on Wisdom (Perception) checks and on saving throws against being blinded, charmed, deafened, frightened, stunned, or knocked unconscious.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'The dog makes two bite attacks.',
        },
        {
          name: 'Bite',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 6, constant: 2 },
          extra:
            'If the target is a creature, it must succeed on a DC 12 Constitution saving throw against disease or become poisoned until the disease is cured. Every 24 hours that elapse, the creature must repeat the saving throw, reducing its hit point maximum by 5 (1d10) on a failure. This reduction lasts until the disease is cured. The creature dies if the disease reduces its hit point maximum to 0.',
        },
      ],
    },
    {
      name: 'Mastiff',
      size: 'medium',
      type: 'beast',
      alignment: 'unaligned',
      armorClass: 12,
      armor: '',
      hitPoints: { throws: 1, sides: 8, constant: 1 },
      speedFt: 40,
      strength: 13,
      dexterity: 14,
      constitution: 12,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
      skills: [{ name: 'Perception', modifier: 3 }],
      senses: ['passive Perception 13'],
      languages: [],
      challengeRating: 0.125,
      passives: [
        {
          name: 'Keen Hearing and Smelling',
          description: 'The mastiff has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
        },
      ],
      actions: [
        {
          name: 'Bite',
          type: 'melee',
          toHit: 3,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 6, constant: 1 },
          extra: 'If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone',
        },
      ],
    },
    {
      name: 'Myling',
      size: 'tiny',
      type: 'undead',
      alignment: 'chaotic evil',
      armorClass: 12,
      armor: '',
      hitPoints: { throws: 11, sides: 8, constant: 0 },
      speedFt: 40,
      strength: 7,
      dexterity: 13,
      constitution: 10,
      intelligence: 10,
      wisdom: 12,
      charisma: 17,
      senses: ['darkvision 60ft.', 'passive Perception 11'],
      damageResistances: [
        'acid, fire, lightning, thunder, bludgeoning, piercing, and slashing from nonmagical attacks',
      ],
      languages: [],
      challengeRating: 5,
      passives: [
        {
          name: 'Pack Tactics',
          description:
            'The thug has advantage on an attack roll against a creature if at least one of the thug’s allies is within 5 ft. of the creature and the ally isn’t incapacitated.',
        },
      ],
      actions: [
        {
          name: 'Withering Touch',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'necrotic',
          damage: { throws: 4, sides: 6, constant: 5 },
        },
        {
          name: 'Etherealness',
          description:
            'The ghost enters the Ethereal Plane from the Material Plane, or vice versa. It is visible on the Material Plane while it is in the Border Ethereal, and vice versa, yet it can’t affect or be affected by anything on the other plane.',
        },
        {
          name: 'Horrifying Visage',
          description:
            'Each non-undead creature within 60 ft. of the ghost that can see it must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute. If the save fails by 5 or more, the target also ages 1d4 x 10 years. A frightened target can repeat the saving throw at the end of each of its turns, ending the frightened condition on itself on a success. If a target’s saving throw is successful or the effect ends for it, the target is immune to this ghost’s Horrifying Visage for the next 24 hours. The aging effect can be reversed with a greater restoration spell, but only within 24 hours of it occurring.',
        },
        {
          name: 'Possession (Recharge 6)',
          description:
            'One humanoid that the ghost can see within 5 ft. of it must succeed on a DC 13 Charisma saving throw or be possessed by the ghost; the ghost then disappears, and the target is incapacitated and loses control of its body. The ghost now controls the body but doesn’t deprive the target of awareness. The ghost can’t be targeted by any attack, spell, or other effect, except ones that turn undead, and it retains its alignment, Intelligence, Wisdom, Charisma, and immunity to being charmed and frightened. It otherwise uses the possessed target’s statistics, but doesn’t gain access to the target’s knowledge, class features, or proficiencies. The possession lasts until the body drops to 0 hit points, the ghost ends it as a bonus action, or the ghost is turned or forced out by an effect like the dispel evil and good spell. When the possession ends, the ghost reappears in an unoccupied space within 5 ft. of the body. The target is immune to this ghost’s Possession for 24 hours after succeeding on the saving throw or after the possession ends.',
        },
      ],
    },
    {
      name: 'Väinämöinen',
      description:
        'Väinämöinen plays a key role in many of the songs and poems of Finnish mythology. He is considered a wise man and one of the best poem singers of all times. He has two brothers, the young skinny Laplander Joukahainen and Ilmarinen, the eternal blacksmith. They are sons of Ilmatar, the goddess of air. The father of the three is unknown. Väinämöinen guards the prison of Perkele at lake Iänlampi.',
      size: 'medium',
      type: 'humanoid (human)',
      alignment: 'lawful good',
      armorClass: 18,
      armor: '',
      hitPoints: { throws: 10, sides: 20, constant: 0 },
      speedFt: 25,
      strength: 9,
      dexterity: 8,
      constitution: 13,
      intelligence: 15,
      wisdom: 17,
      charisma: 15,
      senses: [],
      languages: [],
      challengeRating: 15,
      passives: [],
      actions: [],
    },
    {
      name: 'Joukahainen',
      description:
        'Brother of Väinämöinen and Ilmarinen, son of Ilmatar. A lesser sage compared to Väinämöinen. Wears black robes with a crow foot tied on his heart. Works with the leader of Metsäläiset.',
      size: 'medium',
      type: 'humanoid (human)',
      alignment: 'neutral evil',
      armorClass: 18,
      armor: '',
      hitPoints: { throws: 10, sides: 20, constant: 0 },
      speedFt: 25,
      strength: 9,
      dexterity: 8,
      constitution: 13,
      intelligence: 15,
      wisdom: 17,
      charisma: 15,
      senses: [],
      languages: [],
      challengeRating: 15,
      passives: [],
      actions: [],
    },
    {
      name: 'Perkele',
      size: 'gargantuan',
      type: 'god',
      alignment: 'chaotic evil',
      armorClass: 20,
      armor: '',
      hitPoints: { throws: 10, sides: 20, constant: 0 },
      speedFt: 25,
      strength: 9,
      dexterity: 8,
      constitution: 13,
      intelligence: 15,
      wisdom: 17,
      charisma: 15,
      senses: [],
      languages: [],
      challengeRating: 20,
      passives: [],
      actions: [],
    },
    {
      name: 'Swoldier of the Sword',
      size: 'medium',
      type: 'humanoid',
      alignment: 'lawful good',
      armorClass: 14,
      armor: '',
      hitPoints: { throws: 3, sides: 10, constant: 1 },
      speedFt: 30,
      strength: 14,
      dexterity: 11,
      constitution: 12,
      intelligence: 8,
      wisdom: 10,
      charisma: 9,
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 0.5,
      passives: [],
      actions: [
        {
          name: 'Longsword',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 8, constant: 2 },
        },
        {
          name: 'Longbow',
          type: 'ranged',
          toHit: 4,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 6, constant: 2 },
        },
        {
          name: 'Charge',
          description:
            'The infantryman charges in fury towards his opponent and attacks, dealing double damage on hit. Can be used only once per encounter.',
        },
      ],
    },
    {
      name: 'Commoner',
      size: 'medium',
      type: 'humanoid (any race)',
      alignment: 'any alignment',
      armorClass: 10,
      armor: '',
      hitPoints: { throws: 0, sides: 0, constant: 4 },
      speedFt: 30,
      strength: 10,
      dexterity: 10,
      constitution: 10,
      intelligence: 10,
      wisdom: 10,
      charisma: 10,
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 0,
      actions: [
        {
          name: 'Club',
          type: 'melee',
          toHit: 2,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 1, sides: 4, constant: 0 },
        },
      ],
    },
    {
      name: 'Gray Keep',
      size: 'medium',
      type: 'humanoid (any race)',
      alignment: 'lawful good',
      armorClass: 16,
      armor: '',
      hitPoints: { throws: 2, sides: 8, constant: 2 },
      speedFt: 30,
      strength: 13,
      dexterity: 12,
      constitution: 12,
      intelligence: 10,
      wisdom: 11,
      charisma: 10,
      skills: [{ name: 'Perception', modifier: 2 }],
      senses: ['passive Perception 12'],
      languages: ['common'],
      challengeRating: 0.125,
      actions: [
        {
          name: 'Two-handed Spear',
          type: 'melee',
          toHit: 3,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 8, constant: 1 },
        },
        {
          name: 'Spear',
          type: 'melee',
          toHit: 3,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 6, constant: 1 },
        },
        {
          name: 'Throwing Spear',
          type: 'ranged',
          toHit: 3,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 6, constant: 1 },
        },
      ],
    },
    {
      name: 'Montaja',
      size: 'medium',
      type: 'humanoid (half-elf)',
      alignment: 'lawful evil',
      armorClass: 18,
      armor: '',
      hitPoints: { throws: 2, sides: 8, constant: 16 },
      speedFt: 30,
      strength: 16,
      dexterity: 11,
      constitution: 14,
      intelligence: 11,
      wisdom: 11,
      charisma: 15,
      savingThrows: ['Con +4', 'Wis +2'],
      senses: ['passive Perception 10'],
      languages: ['common', 'elvish', 'giant'],
      challengeRating: 3,
      actions: [
        {
          name: 'Multiattack',
          description: 'Montaja makes two greataxe attacks.',
        },
        {
          name: 'Greataxe',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 2, sides: 6, constant: 3 },
        },
      ],
      reactions: [
        {
          name: 'Parry',
          description:
            'Montaja adds 2 to its AC against one melee attack that would hit it. To do so, Montaja must see the attacker and be wielding a melee weapon.',
        },
      ],
    },
    {
      name: 'Metsäläinen Soldier',
      size: 'medium',
      type: 'humanoid (any race)',
      alignment: 'lawful evil',
      armorClass: 16,
      armor: '',
      hitPoints: { throws: 3, sides: 8, constant: 16 },
      speedFt: 30,
      strength: 17,
      dexterity: 2,
      constitution: 14,
      intelligence: 14,
      wisdom: 11,
      charisma: 12,
      savingThrows: ['Con +4', 'Dex +2'],
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 3,
      actions: [
        {
          name: 'Multiattack',
          description: 'The soldier makes two melee attacks.',
        },
        {
          name: 'Hunting Axe',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 2, sides: 5, constant: 3 },
        },
        {
          name: 'Spear',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 2, sides: 5, constant: 3 },
        },
        {
          name: 'Throwing Spear',
          type: 'ranged',
          toHit: 5,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 2, sides: 5, constant: 3 },
        },
      ],
      reactions: [
        {
          name: 'Parry',
          description:
            'Soldier adds 2 to its AC against one melee attack that would hit it. To do so, soldier must see the attacker and be wielding a melee weapon.',
        },
      ],
    },
    {
      name: 'Metsäläinen Cleric',
      size: 'medium',
      type: 'humanoid (any race)',
      alignment: 'lawful evil',
      armorClass: 14,
      armor: '',
      hitPoints: { throws: 1, sides: 8, constant: 16 },
      speedFt: 30,
      strength: 12,
      dexterity: 12,
      constitution: 14,
      intelligence: 15,
      wisdom: 14,
      charisma: 12,
      savingThrows: ['Wis +2'],
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 3,
      actions: [
        {
          name: 'Spellcasting',
          description:
            'Cleric is a 2nd-level spellcaster. Its spellcasting ability is Wisdom (spell save DC 12, +4 to hit with spell attacks). It has the following sorcerer spells prepared: Cantrips (at will): blade ward, magic missile',
        },
        {
          name: 'Dagger',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 2, sides: 4, constant: 3 },
        },
      ],
    },
    {
      name: 'Ahto Piki',
      size: 'medium',
      type: 'humanoid (male elf)',
      alignment: 'lawful evil',
      armorClass: 12,
      armor: '(15 with Mage armor)',
      hitPoints: { throws: 7, sides: 8, constant: 0 },
      speedFt: 30,
      strength: 9,
      dexterity: 14,
      constitution: 11,
      intelligence: 16,
      wisdom: 12,
      charisma: 11,
      savingThrows: ['Int +5', 'Wis +3'],
      senses: ['passive Perception 10'],
      languages: ['common', 'elvish', 'draconic', 'giant'],
      challengeRating: 5,
      actions: [
        {
          name: 'Spellcasting',
          description:
            'Ahto is a 9th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 14, +5 to hit with spell attacks). Ahto has the following wizard spells prepared:\
            1st level (4 slots): detect magic, mage armor, magic missile, shield 2nd level (3 slots): misty step, suggestion 3rd level (3 slots): counterspell, fireball, fly 4th level (2 slots): greater invisibility, ice storm 5th level (1 slot): cone of cold\
            ',
        },
        {
          name: 'Dagger',
          toHit: 5,
          reachFt: 5,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 4, constant: 2 },
        },
      ],
    },
    {
      name: 'Chief Ikäheimo',
      size: 'small',
      type: 'humanoid (male dwarf)',
      alignment: 'lawful good',
      armorClass: 16,
      armor: '',
      hitPoints: { throws: 12, sides: 8, constant: 45 },
      speedFt: 30,
      strength: 18,
      dexterity: 15,
      constitution: 16,
      intelligence: 10,
      wisdom: 12,
      charisma: 15,
      savingThrows: ['Str +7', 'Dex +2', 'Con +6'],
      senses: ['passive Perception 10'],
      languages: ['common', 'dwarwish'],
      challengeRating: 4,
      passives: [
        {
          name: 'Brave',
          description: 'Ikäheimo has advantage on saving throws against being frightened.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'Ikäheimo makes three melee attacks.',
        },
        {
          name: 'Greataxe',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 2, sides: 8, constant: 4 },
        },
        {
          name: 'Shield Bash',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 2, sides: 4, constant: 4 },
          extra:
            'If the target is a Medium or smaller creature, it must succeed on a DC 15 Strength saving throw or be knocked prone.',
        },
      ],
      reactions: [
        {
          name: 'Parry',
          description:
            'Ikäheimo adds 3 to its AC against one melee attack that would hit it. To do so, the gladiator must see the attacker and be wielding a melee weapon.',
        },
      ],
    },
    {
      name: 'Witch Autere',
      size: 'medium',
      type: 'humanoid (female elf)',
      alignment: 'chaotic good',
      armorClass: 12,
      armor: '(15 with Mage armor)',
      hitPoints: { throws: 7, sides: 8, constant: 0 },
      speedFt: 30,
      strength: 9,
      dexterity: 14,
      constitution: 11,
      intelligence: 16,
      wisdom: 12,
      charisma: 11,
      savingThrows: ['Int +5', 'Wis +3'],
      senses: ['passive Perception 10'],
      languages: ['common', 'elvish'],
      challengeRating: 5,
      actions: [
        {
          name: 'Spellcasting',
          description:
            'Autere is a 9th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 14, +5 to hit with spell attacks). Autere has the following wizard spells prepared: \
            \n1st level (4 slots): detect magic, mage armor, magic missile, shield 2nd level (3 slots): misty step, suggestion 3rd level (3 slots): counterspell, speak with dead, fly 4th level (2 slots): greater invisibility, ice storm 5th level (1 slot): raise dead',
        },
      ],
    },
    {
      name: 'Seer Kaukovalta',
      size: 'medium',
      type: 'humanoid (male human)',
      alignment: 'neutral good',
      armorClass: 12,
      armor: '',
      hitPoints: { throws: 4, sides: 8, constant: 0 },
      speedFt: 30,
      strength: 9,
      dexterity: 12,
      constitution: 11,
      intelligence: 14,
      wisdom: 14,
      charisma: 11,
      savingThrows: ['Wis +3'],
      senses: ['passive Perception 15'],
      languages: ['common'],
      challengeRating: 2,
      actions: [
        {
          name: 'Dagger of Venom',
          toHit: 3,
          reachFt: 5,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 6, constant: 2 },
          extra:
            'That creature must succeed on a DC 15 Constitution saving throw or take 2d10 poison damage and become Poisoned for 1 minute.',
        },
        {
          name: 'Dagger',
          toHit: 3,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 6, constant: 2 },
        },
      ],
    },
    {
      name: 'Kaino Kalpa',
      size: 'medium',
      type: 'humanoid (human male)',
      alignment: 'neutral evil',
      armorClass: 13,
      armor: '',
      hitPoints: { throws: 17, sides: 8, constant: 0 },
      speedFt: 30,
      strength: 10,
      dexterity: 15,
      constitution: 15,
      intelligence: 10,
      wisdom: 10,
      charisma: 3,
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 2,
      actions: [
        {
          name: 'Shortsword',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 6, constant: 3 },
        },
      ],
      reactions: [
        {
          name: 'Parry',
          description:
            'Kaino adds 2 to its AC against one melee attack that would hit it. To do so, Kaino must see the attacker and be wielding a melee weapon.',
        },
      ],
    },
    {
      name: 'Veli Hopea',
      size: 'medium',
      type: 'humanoid (human male)',
      alignment: 'neutral',
      armorClass: 10,
      armor: '',
      hitPoints: { throws: 2, sides: 8, constant: 1 },
      speedFt: 30,
      strength: 10,
      dexterity: 18,
      constitution: 11,
      intelligence: 10,
      wisdom: 12,
      charisma: 16,
      senses: ['passive Perception 12'],
      languages: ['common'],
      challengeRating: 0,
      passives: [
        {
          name: 'Master of Escape',
          description:
            'Veli is an expert in escaping dangerous situations. He can do Disengage as a bonus action and Dash 2.5 times faster than his normal speed (=75ft.)',
        },
      ],
    },
    {
      name: 'Heimo Hallava',
      size: 'medium',
      type: 'humanoid (human male)',
      alignment: 'chaotic neutral',
      armorClass: 10,
      armor: '',
      hitPoints: { throws: 5, sides: 8, constant: 1 },
      speedFt: 30,
      strength: 9,
      dexterity: 9,
      constitution: 12,
      intelligence: 15,
      wisdom: 15,
      charisma: 16,
      senses: ['passive Perception 10'],
      languages: ['common', 'elvish'],
      challengeRating: 0,
      passives: [
        {
          name: 'Always Prepared',
          description: 'Heimo possesses a potion of invisibility that he carries with him everywhere.',
        },
      ],
    },
    {
      name: 'Hellä Pohjanterä',
      size: 'medium',
      type: 'humanoid (human female)',
      alignment: 'neutral evil',
      armorClass: 10,
      armor: '',
      hitPoints: { throws: 10, sides: 8, constant: 0 },
      speedFt: 1,
      strength: 9,
      dexterity: 9,
      constitution: 12,
      intelligence: 16,
      wisdom: 16,
      charisma: 18,
      senses: ['passive Perception 14'],
      languages: ['common'],
      challengeRating: 3,
      passives: [
        {
          name: 'Always Prepared',
          description: 'Hellä possesses a potion of invisibility that he carries with him everywhere.',
        },
      ],
      actions: [
        {
          name: 'Serrated Dagger',
          type: 'melee',
          toHit: 6,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 3, sides: 6, constant: 1 },
        },
      ],
    },
    {
      name: 'Kekko Pohjanterä',
      size: 'medium',
      type: 'humanoid (human male)',
      alignment: 'lawful good',
      armorClass: 14,
      armor: '',
      hitPoints: { throws: 21, sides: 8, constant: 0 },
      speedFt: 30,
      strength: 12,
      dexterity: 14,
      constitution: 13,
      intelligence: 12,
      wisdom: 14,
      charisma: 14,
      senses: ['passive Perception 9'],
      languages: ['common'],
      challengeRating: 2,
      actions: [
        {
          name: 'Longsword',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 10, constant: 10 },
        },
      ],
      reactions: [
        {
          name: 'Parry',
          description:
            'Kekko adds 2 to its AC against one melee attack that would hit it. To do so, Kekko must see the attacker and be wielding a melee weapon.',
        },
      ],
    },
    {
      name: 'Untamo Eteläterä',
      size: 'medium',
      type: 'humanoid (human male)',
      alignment: 'lawful good',
      armorClass: 16,
      armor: '',
      hitPoints: { throws: 21, sides: 8, constant: 0 },
      speedFt: 30,
      strength: 12,
      dexterity: 16,
      constitution: 12,
      intelligence: 13,
      wisdom: 15,
      charisma: 12,
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 2,
      actions: [
        {
          name: 'Longsword',
          type: 'melee',
          toHit: 3,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 10, constant: 10 },
        },
      ],
    },
    {
      name: 'Butler Kalervo',
      size: 'medium',
      type: 'humanoid (human male)',
      alignment: 'lawful good',
      armorClass: 16,
      armor: '',
      hitPoints: { throws: 21, sides: 8, constant: 0 },
      speedFt: 35,
      strength: 12,
      dexterity: 16,
      constitution: 12,
      intelligence: 13,
      wisdom: 15,
      charisma: 12,
      senses: ['passive Perception 12'],
      languages: ['common'],
      challengeRating: 3,
      passives: [
        {
          name: 'Unarmed Defence',
          description: 'While Kalervo is wearing no armor and wielding no shield, its AC includes its Wisdom modifier.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'Kalervo makes two attacks: one with its unarmed attack and one with its Fire Jab.',
        },
        {
          name: 'Unarmed Strike',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 1, sides: 8, constant: 3 },
        },
        {
          name: 'Fire Jab',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'fire',
          damage: { throws: 1, sides: 8, constant: 3 },
        },
        {
          name: 'Three Point Strike (Recharge 5-6)',
          description:
            'Kalervo makes three Unarmed Strike attacks against one target. If two attacks hit, the target is incapacitated. If three attacks hit, the target is stunned. These conditions last until the end of Kalervo’s next turn.',
        },
      ],
      reactions: [
        {
          name: 'Block',
          description: 'Kalervo adds 3 to its AC against one melee attack. To do so, Kalervo must see the attacker.',
        },
      ],
    },
    {
      name: 'Valtari Sinuhe',
      size: 'medium',
      type: 'humanoid (elf male)',
      alignment: 'lawful good',
      armorClass: 18,
      armor: '(Plate armor)',
      hitPoints: { throws: 4, sides: 8, constant: 24 },
      speedFt: 25,
      strength: 16,
      dexterity: 11,
      constitution: 14,
      intelligence: 11,
      wisdom: 13,
      charisma: 15,
      savingThrows: ['Con +4', 'Wis +2'],
      senses: ['passive Perception 10'],
      languages: ['common', 'elvish'],
      challengeRating: 4,
      actions: [
        {
          name: 'Multiattack',
          description: 'Valtari makes two greatsword attacks.',
        },
        {
          name: 'Greatsword',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 2, sides: 6, constant: 5 },
        },
      ],
    },
  ],
})
