module.exports = Object.freeze({
  monsters: [
    {
      name: 'Thug',
      size: 'medium',
      type: 'humanoid',
      alignment: 'any alignment',
      armorClass: 11,
      armor: 'Leather Armor',
      hitPoints: { throws: 2, sides: 8, constant: 10 },
      speedFt: 30,
      strength: 15,
      dexterity: 11,
      constitution: 14,
      intelligence: 10,
      wisdom: 10,
      charisma: 11,
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 0.5,
      passives: [
        {
          name: 'Pack Tactics',
          description:
            'The thug has advantage on an attack roll against a creature if at least one of the thug’s allies is within 5 ft. of the creature and the ally isn’t incapacitated.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'The thug makes two melee attacks.',
        },
        {
          name: 'Mace',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 1, sides: 6, constant: 2 },
        },
      ],
    },
    {
      name: 'Saltwater Scrag',
      size: 'large',
      type: 'giant',
      alignment: 'chaotic evil',
      armorClass: 14,
      armor: '',
      hitPoints: { throws: 8, sides: 10, constant: 40 },
      speedFt: 30,
      strength: 18,
      dexterity: 13,
      constitution: 20,
      intelligence: 7,
      wisdom: 9,
      charisma: 7,
      skills: ['Perception +2'],
      senses: ['darkvision 60ft.', 'passive Perception 12'],
      languages: ['aquan', 'giant'],
      challengeRating: 5,
      passives: [
        {
          name: 'Keen Smell',
          description: 'The Saltwater Scrag has advantage on Wisdom (Perception) checks that rely on smell.',
        },
        {
          name: 'Amphibious',
          description: 'The Saltwater Scrag can breath air and water.',
        },
        {
          name: 'Underwater Regeneration',
          description:
            'While at least partially submerged in salt water, regains 10 hit points at the start of its turn. If takes fire or acid damage, this trait does not function at the start of its next turn. Dies only if starts its turn with 0 hit points and does not regenerate.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'The Saltwater Scrag makes two melee attacks: one with is claws and one with its bite.',
        },
        {
          name: 'Bite',
          type: 'melee',
          toHit: 8,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 10, constant: 5 },
          extra:
            'The target is grappled (escape DC 16). Until this grapple ends, the target is restrained, and The Saltwater Scrag cannot bite another target.',
        },
      ],
    },
    {
      name: 'Northern Giant',
      size: 'large',
      type: 'giant',
      alignment: 'neutral evil',
      armorClass: 13,
      armor: '',
      hitPoints: { throws: 10, sides: 12, constant: 40 },
      speedFt: 35,
      strength: 21,
      dexterity: 8,
      constitution: 19,
      intelligence: 5,
      wisdom: 9,
      charisma: 6,
      skills: ['Perception +2'],
      senses: ['passive Perception 12'],
      damageResistances: ['cold'],
      languages: ['giant'],
      challengeRating: 5,
      passives: [],
      actions: [
        {
          name: 'Multiattack',
          description: 'The giant makes two greatclub attacks.',
        },
        {
          name: 'Greatclub',
          type: 'melee',
          toHit: 8,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 3, sides: 10, constant: 5 },
        },
        {
          name: 'Rock',
          type: 'ranged',
          toHit: 8,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'bludgeoning',
          damage: { throws: 3, sides: 6, constant: 5 },
        },
      ],
    },
    {
      name: 'Swarm of Rats',
      size: 'medium',
      type: 'swarm of tiny beasts',
      alignment: 'unaligned',
      armorClass: 10,
      armor: '',
      hitPoints: { throws: 7, sides: 8, constant: 7 },
      speedFt: 30,
      strength: 9,
      dexterity: 11,
      constitution: 9,
      intelligence: 2,
      wisdom: 10,
      charisma: 3,
      senses: ['darkvision 30ft.', 'passive Perception 10'],
      damageResistances: ['bludgeoning', 'piercing', 'slashing'],
      conditionImmunities: [
        'charmed',
        'frightened',
        'grappled',
        'paralyzed',
        'petrified',
        'prone',
        'restrained',
        'stunned',
      ],
      languages: [],
      challengeRating: 0.25,
      passives: [
        {
          name: 'Keen Smell',
          description: 'The swarm has advantage on Wisdom (Perception) checks that rely on smell.',
        },
        {
          name: 'Swarm',
          description:
            "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny rat. The swarm cannot regain hit points or gain temporary hit points.",
        },
      ],
      actions: [
        {
          name: 'Bite',
          type: 'melee',
          toHit: 2,
          reachFt: 0,
          damageType: 'piercing',
          damage: { throws: 2, sides: 6, constant: 0 },
          extra: '3 (1d6) piercing damage if the swarm has half of its hit points or fewer.',
        },
      ],
    },
    {
      name: 'Körri',
      size: 'tiny',
      type: 'beast',
      alignment: 'neutral evil',
      armorClass: 14,
      armor: '',
      hitPoints: { throws: 2, sides: 4, constant: 0 },
      speedFt: 40,
      strength: 3,
      dexterity: 15,
      constitution: 12,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
      senses: ['darkvision 30ft.', 'passive Perception 13'],
      damageResistances: ['poison'],
      languages: [],
      challengeRating: 0.125,
      passives: [
        {
          name: 'Keen Smell',
          description: 'Körri has advantage on Wisdom (Perception) checks that rely on smell.',
        },
      ],
      actions: [
        {
          name: 'Claws',
          type: 'melee',
          toHit: 2,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 6, constant: 0 },
        },
      ],
    },
    {
      name: 'Bandit Captain',
      size: 'medium',
      type: 'humanoid',
      alignment: 'neutral evil',
      armorClass: 15,
      armor: 'Studded leather',
      hitPoints: { throws: 10, sides: 8, constant: 20 },
      speedFt: 30,
      strength: 15,
      dexterity: 16,
      constitution: 14,
      intelligence: 14,
      wisdom: 11,
      charisma: 14,
      senses: ['passive Perception 10'],
      languages: ['common', 'elvish'],
      challengeRating: 2,
      passives: [],
      actions: [
        {
          name: 'Multiattack',
          description:
            'The captain makes three melee attacks: two with its scimitar and one with its dagger. Or the captain makes two ranged attacks with its daggers.',
        },
        {
          name: 'Scimitar',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 6, constant: 3 },
        },
        {
          name: 'Dagger',
          type: 'melee',
          toHit: 5,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 4, constant: 3 },
        },
        {
          name: 'Dagger',
          type: 'ranged',
          toHit: 5,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 4, constant: 3 },
        },
      ],
      reactions: [
        {
          name: 'Parry',
          description:
            'The captain adds 2 to its AC against one melee attack that would hit it. To do so, the captain must see the attacker and be wielding a melee weapon.',
        },
      ],
    },
    {
      name: 'Bandit',
      size: 'medium',
      type: 'humanoid (any race)',
      alignment: 'neutral evil',
      armorClass: 12,
      armor: 'leather armor',
      hitPoints: { throws: 2, sides: 8, constant: 2 },
      speedFt: 30,
      strength: 11,
      dexterity: 12,
      constitution: 12,
      intelligence: 10,
      wisdom: 10,
      charisma: 10,
      senses: ['passive Perception 10'],
      languages: ['common'],
      challengeRating: 0.125,
      passives: [],
      actions: [
        {
          name: 'Scimitar',
          type: 'melee',
          toHit: 3,
          reachFt: 5,
          damageType: 'slashing',
          damage: { throws: 1, sides: 6, constant: 1 },
        },
        {
          name: 'Light Crossbow',
          type: 'ranged',
          toHit: 3,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 8, constant: 1 },
        },
      ],
    },
    {
      name: 'Kobold',
      size: 'small',
      type: 'humanoid (kobold)',
      alignment: 'lawful evil',
      armorClass: 12,
      armor: 'leather armor',
      hitPoints: { throws: 2, sides: 6, constant: -2 },
      speedFt: 30,
      strength: 7,
      dexterity: 15,
      constitution: 9,
      intelligence: 8,
      wisdom: 7,
      charisma: 8,
      senses: ['passive Perception 18'],
      languages: ['common', 'draconic'],
      challengeRating: 0.125,
      passives: [
        {
          name: 'Sunlight Sensitivity',
          description:
            'While in sunlight, the kobold has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.',
        },
        {
          name: 'Pack Tactics',
          description:
            'The kobold has advantage on an attack roll against a creature if at least one of the kobold’s allies is within 5 ft. of the creature and the ally isn’t incapacitated.',
        },
      ],
      actions: [
        {
          name: 'Dagger',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 4, constant: 2 },
        },
        {
          name: 'Sling',
          type: 'ranged',
          toHit: 4,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'bludgeoning',
          damage: { throws: 1, sides: 4, constant: 2 },
        },
      ],
    },
    {
      name: 'Golem Guardian',
      size: 'large',
      type: 'construct',
      alignment: 'unaligned',
      armorClass: 17,
      armor: '',
      hitPoints: { throws: 17, sides: 10, constant: 85 },
      speedFt: 25,
      strength: 22,
      dexterity: 9,
      constitution: 20,
      intelligence: 3,
      wisdom: 11,
      charisma: 1,
      senses: ['passive Perception 10'],
      languages: ['understands the languages of its creator but can’t speak'],
      challengeRating: 10,
      passives: [
        {
          name: 'Immutable Form',
          description: 'The golem is immune to any spell or effect that would alter its form.',
        },
        {
          name: 'Magic Resistance',
          description: 'The golem has advantage on saving throws against spells and other magical effects.',
        },
        {
          name: 'Magic Weapons',
          description: 'The golem’s weapon attacks are magical.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'The golem makes two slam attacks.',
        },
        {
          name: 'Slam',
          type: 'melee',
          toHit: 10,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 3, sides: 8, constant: 6 },
        },
      ],
    },
    {
      name: 'Deep Gnome',
      size: 'small',
      type: 'humanoid (gnome)',
      alignment: 'neutral good',
      armorClass: 15,
      armor: '(Chain shirt)',
      hitPoints: { throws: 3, sides: 6, constant: 6 },
      speedFt: 20,
      strength: 15,
      dexterity: 14,
      constitution: 14,
      intelligence: 12,
      wisdom: 10,
      charisma: 9,
      senses: ['passive Perception 10'],
      languages: ['gnomish', 'terran', 'undercommon'],
      challengeRating: 0.5,
      passives: [
        {
          name: 'Stone Camouflage',
          description: 'The gnome has advantage on Dexterity (Stealth) checks made to hide in rocky terrain.',
        },
        {
          name: 'Gnome Cunning',
          description: 'The gnome has advantage on Intelligence, Wisdom, and Charisma saving throws against magic.',
        },
        {
          name: 'Innate Spellcasting',
          description:
            'The gnome’s innate spellcasting ability is Intelligence (spell save DC 11). It can innately cast the following spells, requiring no material components:\
          \nCantrips (at will): nondetection (self only) \
          1/day each: blindness, deafness, blur, disguise self',
        },
      ],
      actions: [
        {
          name: 'War Pick',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'piercing',
          damage: { throws: 1, sides: 8, constant: 2 },
        },
        {
          name: 'Poisoned Dart',
          type: 'ranged',
          toHit: 4,
          rangeFt: 20,
          disadvantageRangeFt: 60,
          damageType: 'piercing',
          damage: { throws: 1, sides: 8, constant: 2 },
          extra:
            'The target must succeed on a dc 12 constitution saving throw or be poisoned for 1 minute The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.',
        },
      ],
    },
  ],
})

/*
{
      name: '',
      size: '',
      type: '',
      alignment: '',
      armorClass: 1,
      armor: '',
      hitPoints: { throws: 1, sides: 1, constant: 1 },
      speedFt: 1,
      strength: 1,
      dexterity: 1,
      constitution: 1,
      intelligence: 1,
      wisdom: 1,
      charisma: 1,
      senses: [],
      languages: [],
      challengeRating: 1,
      passives: [
        {
          name: 'Pack Tactics',
          description:
            'The thug has advantage on an attack roll against a creature if at least one of the thug’s allies is within 5 ft. of the creature and the ally isn’t incapacitated.',
        },
      ],
      actions: [
        {
          name: 'Multiattack',
          description: 'The thug makes two melee attacks.',
        },
        {
          name: 'Mace',
          type: 'melee',
          toHit: 4,
          reachFt: 5,
          damageType: 'bludgeoning',
          damage: { throws: 1, sides: 6, constant: 2 },
        },
      ],
    },
*/
