const { test, expect } = require('@playwright/test')

test.describe('Notebook', () => {
  test('edit records', async ({ page }) => {
    await page.goto('/')
    await page.click('.menu-item-button[title="Notebook"]')
    await page.click('.notebook-add-record-button')
    await page.locator('textarea').click()
    await page.locator('textarea').clear()
    await page.locator('textarea').fill("Maukka found his mother's necklace")
    await page.locator('.notebook-record > input').clear()
    await page.locator('.notebook-record > input').fill('First session')
    await page.click('.record-control-button-container > :nth-child(1)')
    await page.click('.notebook-add-record-button')
    await page.locator('.notebook-record > input').clear()
    await page.locator('.notebook-record > input').fill('Second session')
    await page.locator('textarea').click()
    await page.locator('textarea').clear()
    await page.locator('textarea').fill("Maukka died protecting his mother's necklace from robbers")
    await page.click('.record-control-button-container > :nth-child(1)')
    await expect(page.locator('.notebook-record-button')).toHaveCount(2)
    await page.locator('.notebook-search').clear()
    await page.locator('.notebook-search').fill('first')
    await expect(page.locator('.notebook-record-button')).toHaveCount(1)
    await page.click('.notebook-record-button')
    await page.click('.record-control-button-container > :nth-child(2)')
    await page.locator('.notebook-search').clear()
    await page.click(':nth-child(2) > .notebook-record-button')
    await page.click('.record-delete-button')
    await expect(page.locator('.notebook-record-button')).toHaveCount(1)
    await page.click('.menu-item-button[title="Notebook"]')
    await expect(page.locator('.notebook-container')).toHaveCount(0)
  })

  test('search by content', async ({ page }) => {
    await page.goto('/')
    await page.click('.menu-item-button[title="Notebook"]')
    await page.click('.notebook-add-record-button')
    await page.locator('textarea').clear()
    await page.locator('textarea').fill('first')
    await page.click('.record-control-button-container > :nth-child(1)')
    await page.click('.notebook-add-record-button')
    await page.locator('textarea').clear()
    await page.locator('textarea').fill('second')
    await page.locator('.notebook-record > input').clear()
    await page.locator('.notebook-record > input').fill('Title')
    await page.click('.record-control-button-container > :nth-child(1)')
    await page.locator('.notebook-search').clear()
    await page.locator('.notebook-search').fill('second')
    await expect(page.locator('.notebook-record-button')).toHaveCount(1)
    await expect(page.locator('.notebook-record-button')).toHaveText('Title')
  })
})
