const { test, expect } = require('@playwright/test')

test.describe('Party', () => {
  test('edit character', async ({ page }) => {
    await page.goto('/')
    await page.click('[title="Add party member"]')
    await page.locator('.character-name').clear()
    await page.locator('.character-name').fill('Maukka')
    await page.locator('.party table td:nth-child(3) > .stat-input').clear()
    await page.locator('.party table td:nth-child(3) > .stat-input').fill('15')
    await page.locator('.party table td:nth-child(4) > .stat-input').clear()
    await page.locator('.party table td:nth-child(4) > .stat-input').fill('20')
    await page.locator('.party table td:nth-child(5) > .stat-input').clear()
    await page.locator('.party table td:nth-child(5) > .stat-input').fill('20')
    await page.locator('.party table td:nth-child(6) > .stat-input').clear()
    await page.locator('.party table td:nth-child(6) > .stat-input').fill('5')
    await page.locator('.party table td:nth-child(7) > .stat-input').clear()
    await page.locator('.party table td:nth-child(7) > .stat-input').fill('6')
    await page.locator('.party table td:nth-child(8) > .stat-input').clear()
    await page.locator('.party table td:nth-child(8) > .stat-input').fill('30')
    await page.click('.inventory-button')
    await page.locator('textarea').click()
    await page.locator('textarea').clear()
    await page.locator('textarea').fill("Mother's necklace")
    await page.locator('.page').click({ force: true })
    await page.click('.condition-menu-open-button')
    await page.click('[title="frightened"]')
    await page.click('.condition-menu-open-button')
    await page.locator('.page').click({ force: true })
    await page.click('.party table td:nth-child(9) > button')
    page.on('dialog', dialog => dialog.accept())
    await page.locator('.context-menu button').filter({ hasText: 'Delete' }).click()
    await expect(page.locator('.party table tbody')).toBeEmpty()
  })

  test('disable and enable character', async ({ page }) => {
    await page.goto('/')
    await page.click('[title="Add party member"]')
    await page.click('.condition-menu-open-button')
    await page.click('[title="frightened"]')
    await page.click('.party table td > .context-menu-button')
    await page.locator('.context-menu button').filter({ hasText: 'Disable' }).click()
    const inputs = page.locator('.party table td input')
    for (const input of await inputs.all()) {
      await expect(input).toBeDisabled()
    }
    await expect(page.locator('.party table input').first()).toBeDisabled()
    await expect(page.locator('.party table .inventory-button')).toBeDisabled()
    await expect(page.locator('.party table .condition-menu-open-button')).toBeDisabled()
    await expect(page.locator('.party table .active-condition')).toBeDisabled()
  })
})
