describe('Party', () => {
  it('edit character', function () {
    cy.visit('http://localhost:8080/')
    cy.get('[title="Add party member"]').click()
    cy.get('.character-name').clear()
    cy.get('.character-name').type('Maukka')
    cy.get('.party table td:nth-child(3) > .stat-input').clear()
    cy.get('.party table td:nth-child(3) > .stat-input').type('15')
    cy.get('.party table td:nth-child(4) > .stat-input').clear()
    cy.get('.party table td:nth-child(4) > .stat-input').type('20')
    cy.get('.party table td:nth-child(5) > .stat-input').clear()
    cy.get('.party table td:nth-child(5) > .stat-input').type('20')
    cy.get('.party table td:nth-child(6) > .stat-input').clear()
    cy.get('.party table td:nth-child(6) > .stat-input').type('5')
    cy.get('.party table td:nth-child(7) > .stat-input').clear()
    cy.get('.party table td:nth-child(7) > .stat-input').type('6')
    cy.get('.party table td:nth-child(8) > .stat-input').clear()
    cy.get('.party table td:nth-child(8) > .stat-input').type('30')
    cy.get('.inventory-button > img').click()
    cy.get('textarea').click()
    cy.get('textarea').clear()
    cy.get('textarea').type("Mother's necklace")
    cy.get('.page').click({ force: true })
    cy.get('.condition-menu-open-button').click()
    cy.get('[title="frightened"]').click()
    cy.get('.condition-menu-open-button').click()
    cy.get('.page').click({ force: true })
    cy.get('.party table td:nth-child(9) > button').click()
    cy.get('.party table tbody').should('be.empty')
  })
})
