name: Release
on:
  push:
    branches: [ master ]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    uses: ./.github/workflows/tests.yml
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npx semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
