name: Tests

on: [pull_request, workflow_call]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - name: Validate campaign.js
        run: npm run validate
      - run: npm run eslint
      - run: npm test
      - run: npm run build
      - name: npm test:cypress
        uses: cypress-io/github-action@v6
        with:
          start: npx http-server dist -p 8080
