name: Tests

on: [pull_request, workflow_call]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - name: Validate campaign.js
        run: npm run validate
      - run: npm run eslint
      - run: npm test
      - run: npm run build
      - name: npm test:cypress
        uses: cypress-io/github-action@v2
        with:
          start: npx http-server dist -p 8080
